name: Linting with Vale on pull request

on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        continue-on-error: true
        with:
          filter_mode: added
          vale_flags: "--no-exit --minAlertLevel=error"
          reporter: github-pr-review
          fail_on_error: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REVIEWDOG_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
